/bin/bash: /data/users2/bthapaliya/anaconda-main/anaconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)
arctrdgn001
Traceback (most recent call last):
  File "/data/users2/bthapaliya/DistributedFLExperiments/DistributedFL/fedml_experiments/standalone/subavg/main_subavg.py", line 198, in <module>
    logger = logger_config(log_path='LOG/' + args.dataset + '/' + args.identity + '.log', logging_name=args.identity)
  File "/data/users2/bthapaliya/DistributedFLExperiments/DistributedFL/fedml_experiments/standalone/subavg/main_subavg.py", line 33, in logger_config
    handler = logging.FileHandler(log_path, mode='w',encoding='UTF-8')
  File "/data/users2/bthapaliya/anaconda-main/anaconda3/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/data/users2/bthapaliya/anaconda-main/anaconda3/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/data/users2/bthapaliya/DistributedFLExperiments/DistributedFL/fedml_experiments/standalone/subavg/LOG/cifar10/SubAVGdir0.3-mdlresnet18original-cm500-total_clnt100-neighbor10-seed2022-dr0.5.log'
